### ISSUE TITLE
Target group healtcheck always fails and ssh isn't accessible

### ISSUE THREAD

**Issue by imesic-kolibree** [joshuamkite/terraform-aws-ssh-bastion-service#17]
I am trying to set up the `bastion` host from scratch in a new VPC. When I deploy, LB targets report as _unhealthy_. This is the code I used:

```terraform

provider "aws" {}
data "aws_availability_zones" "available" {}

resource "aws_vpc" "bastion" {
  cidr_block           = "10.50.0.0/16"
  enable_dns_hostnames = true
}

resource "aws_subnet" "bastion" {
  count = 2

  availability_zone = "${data.aws_availability_zones.available.names[count.index]}"
  cidr_block        = "10.50.${count.index}.0/24"
  vpc_id            = "${aws_vpc.bastion.id}"
}

resource "aws_internet_gateway" "bastion" {
  vpc_id = "${aws_vpc.bastion.id}"
}

resource "aws_route_table" "bastion" {
  vpc_id = "${aws_vpc.bastion.id}"
}

resource "aws_route" "bastion-ipv4-out" {
  route_table_id         = "${aws_route_table.bastion.id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway.bastion.id}"
}

resource "aws_route_table_association" "bastion" {
  count = 2

  subnet_id      = "${aws_subnet.bastion.*.id[count.index]}"
  route_table_id = "${aws_route_table.bastion.id}"
}

variable "everyone-cidr" {
  default     = "0.0.0.0/0"
  description = "Everyone"
}

module "ssh-bastion-service" {
  source                   = "joshuamkite/ssh-bastion-service/aws"
  version                  = "4.4.0"

  aws_region  = "${var.aws-region}"
  aws_profile = "${var.profile-name"

  environment_name = "${var.cluster-name}"
  vpc              = "${aws_vpc.bastion.id}"

  bastion_allowed_iam_group = "bastion_users"
  assume_role_arn           = "${var.master_bastion_role_arn}"

  dns_domain      = "example.com"
  route53_zone_id = "${var.route53-zone-id}"

  subnets_asg = ["${aws_subnet.bastion.*.id}"]
  subnets_lb  = ["${aws_subnet.bastion.*.id}"]

  cidr_blocks_whitelist_service = ["${var.everyone-cidr}"]

  bastion_service_host_key_name = "${var.key-name}"
}
```

If I update https://github.com/joshuamkite/terraform-aws-ssh-bastion-service/blob/master/main.tf#L31 manually to `true`, then everything works.

What would be the issue with my setup? I do not want to use a NAT Gateway (it's a bit pricey to use for this use case).

From my limited debugging, it seems that the host instance doesn't have access to the internet but I'm not sure if that is the issue. I added a key-pair to the bastion host instance and launched a new EC2 instance in the same VPC (with a public IP) and from it ssh-ed to the bastion host. The network is unreachable: 
```
admin@ip-10-50-0-155:~$ curl -v http://google.com
* Rebuilt URL to: http://google.com/
*   Trying 74.125.193.100...
* TCP_NODELAY set
*   Trying 2a00:1450:400b:c01::66...
* TCP_NODELAY set
* Immediate connect fail for 2a00:1450:400b:c01::66: Network is unreachable
```

Other than that, I don't know what to check and how to debug what is wrong.

**Comment by joshuamkite** [comment]
I think you may have misunderstood the role of the DNS domain here. If you give a value for  `route_53_zone_id` then this module will attempt to create a public DNS record. the Zone ID and DNS domain must match - which they cannot here with 'Example.com'. I would suggest that you leave this blank for the module and do your DNS stuff externally to the module in your plan.

This plan creates a load balancer which should have a public IP and direct traffic to the targets. Ideally the autoscaling group should be in a private subnet, although it has been tested with the same subnets for both. The load balancer needs to be whitelisted on the healthcheck port in order for instances to be considered healthy. This plan always tries to give the bastion access to the internet with

    resource "aws_security_group_rule" "bastion_host_out" {
    type              = "egress"
    from_port         = 0
    to_port           = 65535
    protocol          = -1
    security_group_id = "${aws_security_group.bastion_service.id}"
    cidr_blocks       = ["0.0.0.0/0"]
    description       = "bastion service and host egress"
    }

The above is added to a security group

`name_prefix            = "${var.environment_name}-bastion-service"`

and I see that you have set 

`environment_name = "${var.cluster-name}"`

There may be something strange here with your config

If you manually create an instance in (one of) the same subnet- are you able to reach it and the internet?

**Comment by imesic-kolibree** [comment]
Thanks for a quick response!

* Sorry for confusion, DNS part works fine, I just redacted the actual one. With the proper name (and the change I mentioned), it creates everything properly.
* Load balancer is created, there is a public ip and there is a listener on port 22 to a target group which has the EC2 instance.
* Security group which allows egress from the host is also created and when I check the EC2 instance, outbound rules are correct.

If I manually create a new instance in one of the subnets I can't access it (it gets only a private IP). 

I did the following now: created a new machine in the same subnet but with a public IP and the same key pair. ssh-ed to it and using that same key then ssh-ed to bastion host machine. No internet access. Maybe interesting that docker is not installed on the host. Scripts in /var/lib/cloud/instance/scripts/ look OK but I found some errors in /var/log/cloud-init.log:
```
2019-01-07 11:45:37,103 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/extra_user_data [-]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1823, in subp
    env=env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 802, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1841, in subp
    errno=e.errno)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/extra_user_data']
Exit code: -
Reason: [Errno 8] Exec format error
Stdout: -
Stderr: -
2019-01-07 11:45:37,135 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/module_docker_setup'] with allowed return codes [0] (shell=False, capture=False)
2019-01-07 12:14:41,118 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/module_docker_setup [127]
2019-01-07 12:14:41,118 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/module_docker_setup [127]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 802, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1850, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/module_docker_setup']
Exit code: 127
Reason: -
Stdout: -
Stderr: -
2019-01-07 12:14:41,119 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/module_iam-authorized-keys-command'] with allowed return codes [0] (shell=False, capture=False)
2019-01-07 12:28:42,847 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/module_iam-authorized-keys-command [127]
2019-01-07 12:28:42,848 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/module_iam-authorized-keys-command [127]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 802, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1850, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/module_iam-authorized-keys-command']
Exit code: 127
Reason: -
Stdout: -
Stderr: -
```

**Comment by imesic-kolibree** [comment]
> I'm not sure I am clear. What I meant is - if you create a similar ec2 instance manually, can that instance access the internet itself?. The behaviour you are describing sounds like a private subnet- you can assign a public ip but you won't be able to reach it.

I guess I don't understand something here. How would I check if the instance can access the internet if I don't assign it a public IP? If I read the documentation correctly (https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html), in order for an EC2 instance in a subnet to have access to the internet it must have a public IP (either a public IP or an Elastic IP), otherwise the packets can't find their way back.

That is why I was launching an instance into the same subnet but with a public IP so I can ssh there and check. But then, that instance has internet access and the bastion host doesn't. The VPC and subnets are created exactly as in the code I posted (as they have the route to the Internet Gateway, both subnets are public).

---
Health check eventually turns to 'Available', but only after all of the custom scripts have finished executing. And that blocks for long time as the timeout is quite long. The previous output shows that, i.e. `module_docker_setup`  blocked for almost 30 minutes.

---

Setting `extra_user_data_content = "#!/bin/bash"` works.

**Comment by joshuamkite** [comment]
Ok, thanks for the link to the documentation which I have glanced through and also for your further investigations. I have only tested this code in either a default VPC or a VPC created with NAT gateways. If I understand you correctly, then as it stands, this module currently has an implicit dependency on a NAT gateway. I note that you have previously said that:
* You wish to avoid using a NAT gateway for your use case
* Setting `public_ip = "true"` in the autoscaling group config fixes this issue for you

I propose then to publish a new version where it is possible (but historic behaviour remains default) to set `public_ip = "true"` where this module is being run without a NAT gateway.

Thank you for confirming that Setting `extra_user_data_content = "#!/bin/bash"` works. This also needs to be an over-rideable default in the next version. The code snippet previously suggested is almost but not quite correct.

Now - would you like to submit pull requests for either or both of the above fixes and be a contributor? If not then I am more than happy to implement them myself.

Thanks VM

**Comment by imesic-kolibree** [comment]
Thank you for the help (and this module)!

I'd be happy to submit a pull request, will do that tomorrow.

Cheers,
Ivan

**Comment by navi7** [comment]
PR for `public_ip`: https://github.com/joshuamkite/terraform-aws-ssh-bastion-service/pull/20
