### ISSUE TITLE
Support for saml based ssh access

### ISSUE THREAD

**Issue by rverma-nikiai** [joshuamkite/terraform-aws-ssh-bastion-service#28]
Will it be possible to use federated user based login with this module? If yes what is the recommended way to implement this? We have federated users attached with roles and would love to use the same here.

**Comment by joshuamkite** [comment]
Firstly, I am not an expert on AWS federated access. Secondly, it is possible to set your own user data for this module to behave in a very different way to default.

I am afraid that it is doubtful that you could use this module **directly** with federated users- but see next paragraph. It is based around IAM identities and SSH keys being associated with them. Single Sign On solutions usually work by using an external authority to authenticate users and give them a token which is accepted by subscribed clients. Federated users are handled in just this way with AWS. AWS provides ssh-key storage for IAM users to access AWS codecommit but for federated users there is a credentials-assistant which tokenises git authentication. What this means is that with federated login there is no ssh-key passed through for this bastion to use and there is no user to reference.

You probably want to look into SSH certificate signing, as used by [Facebook](https://code.fb.com/security/scalable-and-secure-access-with-ssh/) and [Netflix](https://github.com/Netflix/bless). Once you had set up such a Certificate Authority, you could then **write your custom user data to use this module**, taking out the IAM stuff and substituting it with config to trust the certificate authority. With this solution, you would keep self service user key management and a containerised and stateless bastion with high availability etc but everyone would be logging in as a common user, e.g. 'root'
