### ISSUE TITLE
Fargate deployment

### ISSUE THREAD

**Issue by cristim** [joshuamkite/terraform-aws-ssh-bastion-service#3]
Have you considered running this as a Fargate ECS container?

Do you think this would be doable?

**Comment by joshuamkite** [comment]
The issue with any sort of scheduler as a service is how to trigger the container activation. I haven't looked at Fargate specifically but when I considered Kubernetes for instance (before AWS EKS was even on the horizon)  I struggled to find a suitable load balancer proxy to do so. Traefik looked good for instance but like almost all of these solutions is only really for http/s and we need tcp.

**Comment by joshuamkite** [comment]
Closing as no further comment
