### ISSUE TITLE
SSH configurations for instances in private subnets

### ISSUE THREAD

**Issue by antonbabenko** [joshuamkite/terraform-aws-ssh-bastion-service#35]
This module creates bastion host resources in public subnets - this is clear, and works as expected.

Do you have an example of what I should have to do on instances that I want to jump to from the bastion host? They are residing in private subnets. Should I put some shared SSH keys to them, or what? I don't seem to find a solution for that in examples and in README.

Thank you in advance!

**Comment by joshuamkite** [comment]
There are a lot of options with this module but in a best practice scenario you would put the _load balancer_ in the public subnet(s) and the host autoscaling group in the _private subnet(s)_ alongside whatever else you want to reach via the bastion.

It might not be obvious but if what you are trying to jump to are other EC2 instances then this is the section in the readme you are looking for:

If you are seeking a solution for ECS hosts then you are recommended to the [Widdix project](https://github.com/widdix/aws-ec2-ssh). This offers IAM authentication for local users with a range of features suitable for a long-lived stateful host built as an AMI or with configuration management tools.

**Comment by antonbabenko** [comment]
Thank you for your answer!

I will probably invest time in making use of [Amazon EC2 Instance Connect ](https://aws.amazon.com/blogs/compute/new-using-amazon-ec2-instance-connect-for-ssh-access-to-your-ec2-instances/).
