### ISSUE TITLE
Feature request: launch template & Spot instance support

### ISSUE THREAD

**Issue by jasonyihk** [joshuamkite/terraform-aws-ssh-bastion-service#46]
It would be nice to support launch template with support on spot instance, which will further reduce operation cost, since already running everything in stateless docker container.

**Comment by joshuamkite** [comment]
I haven't had a lot of time to implement this but if it's a feature that you'd like to contribute, that would be very welcome! [One of the many forks of this project has implemented it](https://github.com/getndazn/terraform-aws-ssh-bastion-service/blob/master/main.tf)
