### ISSUE TITLE
https://registry.terraform.io/providers/hashicorp/template/ is deprecated, and prevents usage on OSX

### ISSUE THREAD

**Issue by lremes** [joshuamkite/terraform-aws-ssh-bastion-service#51]
When attempting to use the module on OSX, I get an error:
```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have
│ different platforms supported
```
The template provider is deprecated, and should be replaced.
https://registry.terraform.io/providers/hashicorp/template/latest/docs

**Comment by joshuamkite** [comment]
I wasn't aware that the `template` provider was not supported on darwin_arm64 . Although I am aware that it is deprecated, the 'replacement' feature does not allow the same facility to conditionally render a file from a template as has been used heavily in this module. I am exploring alternative approaches.

**Comment by joshuamkite** [comment]
I have a new version currently in feature branch which preserves existing functionality whilst retiring the deprecated `template` and `null_resource` providers. It seems fine with linux amd64 Perhaps you could be kind enough to test it for basic functionality on darwin_arm64 and let me know how you get on.  You can do so calling the module with 
```terraform
source = "git@github.com:joshuamkite/terraform-aws-ssh-bastion-service.git?ref=issue_51/template_file"
```
If I don't hear from you within a week or so I will presume that you are no longer available to continue this conversation

Thanks

**Comment by joshuamkite** [comment]
This is resolved in latest relese
